name: gelectrical
adopt-info: gelectrical
license: GPL-3.0+
icon: snap/gui/gelectrical.svg
description: |
    GElectrical is a free and opensource electrical system analysis software for LV/MV electrical distribution networks. Following features are currently implemented.

    * Schematic capture.
    * Pandapower network generation from schematic.
    * Power flow time series analysis (Symmetric and Assymetric).
    * Power flow with diversity factors (Symmetric and Assymetric).
    * Voltage drop analysis.
    * Short circuit analysis (Symmetric and SLG).
    * Coordination analysis for power supply protection devices with support for CB and fuse protection curves; damage curves for transformers, cables and motors.
    * Support for daily load curves for load elements.
    * Support for arriving network parameters for custom geometry OH lines.
    * Support for modeling networks with mixed TN-S/ TN-C/ TT/ IT earthing systems.
    * Electrical rules check for checking conformity with IEC/ local electrical guidelines.
    * Print and export of drawings to pdf.
    * Generation of analysis reports.

    GElectrical uses pandapower as the backend for implementing power flow related functionality like voltage drop and short circuit analysis.
    
    
grade: stable
base: core22
confinement: strict

apps:
  gelectrical:
    command: /bin/gelectrical_launcher.py
    extensions: [gnome]
    plugs:
      - home
      - removable-media
    slots:
      - gelectrical
    common-id: com.kavilgroup.gelectrical
    
slots:
  gelectrical:
    interface: dbus
    bus: session
    name: com.kavilgroup.gelectrical

parts:
  gelectrical:
    plugin: python
    source: .
    python-requirements: [requirements.txt]
    build-packages:
      - libgeos-dev
    stage-packages:
      - geos-bin
    parse-info: [app/share/metainfo/com.kavilgroup.gelectrical.appdata.xml]
    
  copyexec:
   plugin: dump
   source: .
   organize:
     gelectrical_launcher.py: bin/gelectrical_launcher.py
   stage:
     - bin/gelectrical_launcher.py

